# Site settings
title: MultiBoot USB
description: >
  This repository stores the files needed to create a pendrive capable of
  booting different ISO files using GRUB2
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock

# Theme settings
show_downloads: true

# Kramdown settings
kramdown:
  syntax_highlighter_opts:
    default_lang: shell
